from dataclasses import dataclass, field


@dataclass
class Course:
    id: str
    title: str
    provider: str
    url: str
    tags: list[str]
    level: str          # beginner | intermediate | advanced
    description: str
    quality_score: float = 0.8


COURSES: list[Course] = [
    # --- ML / AI ---
    Course("ml-001", "Machine Learning Specialization", "Coursera / DeepLearning.AI",
           "https://www.coursera.org/specializations/machine-learning-introduction",
           ["machine_learning", "python", "scikit_learn"],
           "intermediate", "Andrew Ng's updated ML course. Covers supervised learning, neural networks, and best practices.", 0.97),
    Course("ml-002", "Deep Learning Specialization", "Coursera / DeepLearning.AI",
           "https://www.coursera.org/specializations/deep-learning",
           ["deep_learning", "python", "tensorflow"],
           "intermediate", "5-course series on neural networks, CNNs, RNNs, and transformers.", 0.96),
    Course("ml-003", "Fast.ai Practical Deep Learning", "fast.ai",
           "https://course.fast.ai",
           ["deep_learning", "python", "pytorch"],
           "intermediate", "Top-down, practical deep learning. Uses PyTorch. Ideal for practitioners.", 0.93),
    Course("ml-004", "LLM Engineering: Master AI & LLMs", "Udemy",
           "https://www.udemy.com/course/llm-engineering-master-ai-and-large-language-models/",
           ["llm", "python", "rag", "langchain"],
           "intermediate", "Build production LLM apps with RAG, agents, and fine-tuning.", 0.88),
    Course("ml-005", "Hugging Face NLP Course", "Hugging Face",
           "https://huggingface.co/learn/nlp-course/chapter1/1",
           ["llm", "nlp", "python", "transformers"],
           "intermediate", "Free official course covering transformers, tokenization, and fine-tuning.", 0.92),
    Course("ml-006", "MLOps Specialization", "Coursera / DeepLearning.AI",
           "https://www.coursera.org/specializations/machine-learning-engineering-for-production-mlops",
           ["mlops", "machine_learning", "python"],
           "advanced", "Production ML systems: deployment, monitoring, data and model pipelines.", 0.90),
    Course("ml-007", "Applied AI with DeepLearning", "Coursera / IBM",
           "https://www.coursera.org/learn/ai",
           ["deep_learning", "python", "tensorflow"],
           "intermediate", "IBM course on deep learning applications with Keras and TensorFlow.", 0.82),
    Course("ml-008", "LangChain for LLM Application Development", "DeepLearning.AI",
           "https://www.deeplearning.ai/short-courses/langchain-for-llm-application-development/",
           ["llm", "langchain", "python", "rag"],
           "intermediate", "Short course by Harrison Chase (LangChain creator). Build chains and agents.", 0.91),
    Course("ml-009", "Building Systems with the ChatGPT API", "DeepLearning.AI",
           "https://www.deeplearning.ai/short-courses/building-systems-with-chatgpt/",
           ["llm", "python", "api"],
           "intermediate", "Multi-step pipelines, chain-of-thought, and evaluation using the OpenAI API.", 0.89),
    Course("ml-010", "Vector Databases: from Embeddings to Applications", "DeepLearning.AI",
           "https://www.deeplearning.ai/short-courses/vector-databases-embeddings-applications/",
           ["llm", "vector_db", "python", "embeddings"],
           "intermediate", "Weaviate-based short course on vector search and embedding-driven apps.", 0.87),

    # --- Data Engineering ---
    Course("de-001", "Data Engineering Zoomcamp", "DataTalks.Club",
           "https://github.com/DataTalksClub/data-engineering-zoomcamp",
           ["data_engineering", "python", "airflow", "spark", "gcp"],
           "intermediate", "Free cohort-based bootcamp covering Spark, Airflow, dbt, BigQuery, and Kafka.", 0.95),
    Course("de-002", "Apache Kafka for Beginners", "Udemy / Stephane Maarek",
           "https://www.udemy.com/course/apache-kafka/",
           ["data_engineering", "kafka", "streaming"],
           "beginner", "Hands-on Kafka: producers, consumers, partitions, streams.", 0.90),
    Course("de-003", "The Ultimate dbt Bootcamp", "Udemy",
           "https://www.udemy.com/course/complete-dbt-data-build-tool-bootcamp-zero-to-hero-learn-dbt/",
           ["data_engineering", "dbt", "sql", "analytics_engineering"],
           "beginner", "Zero-to-hero dbt course. Models, tests, docs, snapshots.", 0.88),
    Course("de-004", "Apache Spark with Python — PySpark", "Udemy",
           "https://www.udemy.com/course/apache-spark-programming-in-python-for-beginners/",
           ["data_engineering", "spark", "python"],
           "beginner", "PySpark essentials: RDDs, DataFrames, Spark SQL, Streaming.", 0.86),
    Course("de-005", "Fundamentals of Data Engineering", "O'Reilly",
           "https://www.oreilly.com/library/view/fundamentals-of-data/9781098108298/",
           ["data_engineering", "architecture"],
           "intermediate", "Joe Reis & Matt Housley's book on the full data lifecycle. Must-read.", 0.94),
    Course("de-006", "Airflow Fundamentals", "Astronomer Academy",
           "https://academy.astronomer.io/astronomer-certification-apache-airflow-fundamentals",
           ["data_engineering", "airflow", "python"],
           "beginner", "Official Airflow certification prep. DAGs, operators, scheduling.", 0.88),

    # --- Cloud / AWS ---
    Course("aws-001", "AWS Certified Solutions Architect – Associate", "Udemy / Stephane Maarek",
           "https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/",
           ["aws", "cloud", "architecture"],
           "intermediate", "Top-rated SAA-C03 prep course. EC2, S3, RDS, VPC, IAM, and more.", 0.95),
    Course("aws-002", "AWS Certified Developer – Associate", "Udemy / Stephane Maarek",
           "https://www.udemy.com/course/aws-certified-developer-associate-dva-c01/",
           ["aws", "cloud", "serverless"],
           "intermediate", "Developer-focused AWS cert: Lambda, DynamoDB, API Gateway, CodePipeline.", 0.93),
    Course("aws-003", "AWS SageMaker Studio for ML", "Udemy",
           "https://www.udemy.com/course/aws-sagemaker-studio/",
           ["aws", "machine_learning", "mlops"],
           "intermediate", "End-to-end ML on AWS: training, tuning, deploying, and monitoring models.", 0.84),
    Course("gcp-001", "Google Cloud Professional Data Engineer", "Coursera / Google",
           "https://www.coursera.org/professional-certificates/gcp-data-engineering",
           ["gcp", "data_engineering", "bigquery"],
           "intermediate", "Official Google cert prep. BigQuery, Dataflow, Pub/Sub, Dataproc.", 0.90),
    Course("gcp-002", "Machine Learning on Google Cloud", "Coursera / Google",
           "https://www.coursera.org/specializations/machine-learning-tensorflow-gcp",
           ["gcp", "machine_learning", "tensorflow"],
           "intermediate", "TensorFlow on GCP, Vertex AI, and scalable ML pipelines.", 0.87),

    # --- DevOps / Kubernetes ---
    Course("k8s-001", "Certified Kubernetes Administrator (CKA)", "Udemy / Mumshad Mannambeth",
           "https://www.udemy.com/course/certified-kubernetes-administrator-with-practice-tests/",
           ["kubernetes", "devops", "docker"],
           "advanced", "The definitive CKA prep with killer.sh-level labs.", 0.96),
    Course("k8s-002", "Docker and Kubernetes: The Complete Guide", "Udemy / Stephen Grider",
           "https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/",
           ["docker", "kubernetes", "devops"],
           "beginner", "Full-stack Docker + K8s from scratch. Includes CI/CD and production deploys.", 0.93),
    Course("k8s-003", "Terraform for Beginners", "Udemy",
           "https://www.udemy.com/course/terraform-beginner-to-advanced/",
           ["terraform", "devops", "aws", "infrastructure_as_code"],
           "beginner", "Infrastructure as code with Terraform. AWS, Azure, GCP providers.", 0.89),
    Course("k8s-004", "CI/CD with GitHub Actions", "Udemy",
           "https://www.udemy.com/course/github-actions/",
           ["devops", "ci_cd", "github"],
           "beginner", "Automate build, test, and deploy workflows with GitHub Actions.", 0.86),
    Course("k8s-005", "GitLab CI: Pipelines, CI/CD and DevOps", "Udemy",
           "https://www.udemy.com/course/gitlab-ci-pipelines-ci-cd-and-devops-for-beginners/",
           ["devops", "ci_cd", "gitlab"],
           "beginner", "Build automated pipelines for containerized applications.", 0.83),

    # --- System Design ---
    Course("sd-001", "Grokking the System Design Interview", "Educative",
           "https://www.educative.io/courses/grokking-the-system-design-interview",
           ["system_design", "architecture", "distributed_systems"],
           "intermediate", "Industry-standard system design interview prep. URL shortener, Twitter, Netflix.", 0.92),
    Course("sd-002", "Grokking Modern System Design for Software Engineers & Managers", "Educative",
           "https://www.educative.io/courses/grokking-modern-system-design-interview-for-engineers-managers",
           ["system_design", "architecture", "distributed_systems"],
           "advanced", "Deep dives into load balancers, CDNs, pub-sub, databases, and caches.", 0.91),
    Course("sd-003", "Designing Data-Intensive Applications", "O'Reilly",
           "https://www.oreilly.com/library/view/designing-data-intensive-applications/9781491903063/",
           ["system_design", "distributed_systems", "databases"],
           "advanced", "Martin Kleppmann's classic on replication, partitioning, and distributed transactions.", 0.98),
    Course("sd-004", "Software Architecture & Technology of Large-Scale Systems", "Udemy",
           "https://www.udemy.com/course/developer-to-architect/",
           ["system_design", "architecture", "distributed_systems"],
           "advanced", "Event-driven architecture, microservices patterns, and fault tolerance.", 0.87),

    # --- Python ---
    Course("py-001", "Python Bootcamp: Zero to Hero", "Udemy / Jose Portilla",
           "https://www.udemy.com/course/complete-python-bootcamp/",
           ["python"],
           "beginner", "Most-starred Python course on Udemy. OOP, decorators, file I/O, web scraping.", 0.91),
    Course("py-002", "Python for Data Science and Machine Learning Bootcamp", "Udemy",
           "https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/",
           ["python", "data_science", "machine_learning", "pandas"],
           "beginner", "Pandas, NumPy, Matplotlib, Seaborn, Scikit-Learn in one course.", 0.90),
    Course("py-003", "Advanced Python: Concurrency & Parallelism", "Real Python",
           "https://realpython.com/learning-paths/python-concurrency-parallel-programming/",
           ["python", "async", "concurrency"],
           "advanced", "asyncio, threading, multiprocessing, and concurrent.futures in depth.", 0.88),
    Course("py-004", "FastAPI — The Complete Course", "Udemy",
           "https://www.udemy.com/course/fastapi-the-complete-course/",
           ["python", "fastapi", "api"],
           "intermediate", "Build production REST APIs with FastAPI, SQLAlchemy, JWT, and Docker.", 0.89),
    Course("py-005", "Python Testing with pytest", "O'Reilly",
           "https://www.oreilly.com/library/view/python-testing-with/9781680502848/",
           ["python", "testing"],
           "intermediate", "Brian Okken's guide to pytest, fixtures, plugins, and TDD.", 0.87),

    # --- TypeScript / React ---
    Course("ts-001", "TypeScript: The Complete Developer's Guide", "Udemy / Stephen Grider",
           "https://www.udemy.com/course/typescript-the-complete-developers-guide/",
           ["typescript", "javascript"],
           "intermediate", "Deep TS: generics, decorators, design patterns, integration with React.", 0.93),
    Course("ts-002", "React — The Complete Guide (incl. React Router & Redux)", "Udemy / Max Schwarzmüller",
           "https://www.udemy.com/course/react-the-complete-guide-incl-redux/",
           ["react", "typescript", "javascript"],
           "beginner", "Hooks, context, Redux Toolkit, Next.js, and full MERN stack.", 0.94),
    Course("ts-003", "Next.js & React — The Complete Guide", "Udemy / Max Schwarzmüller",
           "https://www.udemy.com/course/nextjs-react-the-complete-guide/",
           ["react", "typescript", "nextjs"],
           "intermediate", "App Router, SSR, ISR, API routes, authentication, and deployment.", 0.91),
    Course("ts-004", "Node.js, Express, MongoDB & More: The Complete Bootcamp", "Udemy / Jonas Schmedtmann",
           "https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/",
           ["typescript", "javascript", "nodejs", "mongodb"],
           "intermediate", "MVC, REST APIs, auth with JWT, MongoDB, and deployment on Heroku.", 0.90),

    # --- Go ---
    Course("go-001", "Go: The Complete Developer's Guide (Golang)", "Udemy / Stephen Grider",
           "https://www.udemy.com/course/go-the-complete-developers-guide/",
           ["golang"],
           "beginner", "Concurrency patterns, interfaces, testing, and building a CLI tool in Go.", 0.91),
    Course("go-002", "Learn How To Code: Google's Go (golang) Programming Language", "Udemy",
           "https://www.udemy.com/course/learn-how-to-code/",
           ["golang"],
           "beginner", "Todd McLeod's comprehensive Go fundamentals: goroutines, channels, packages.", 0.88),
    Course("go-003", "Building Microservices with Go", "Udemy",
           "https://www.udemy.com/course/working-with-microservices-in-go/",
           ["golang", "microservices", "docker"],
           "advanced", "gRPC, REST, RabbitMQ, Docker, and Kubernetes with idiomatic Go.", 0.86),

    # --- Databases / SQL ---
    Course("db-001", "The Complete SQL Bootcamp: Zero to Hero", "Udemy / Jose Portilla",
           "https://www.udemy.com/course/the-complete-sql-bootcamp/",
           ["sql", "databases", "postgresql"],
           "beginner", "PostgreSQL fundamentals: queries, joins, aggregations, window functions.", 0.92),
    Course("db-002", "SQL and PostgreSQL: The Complete Developer's Guide", "Udemy",
           "https://www.udemy.com/course/sql-and-postgresql/",
           ["sql", "postgresql", "databases"],
           "intermediate", "Subqueries, CTEs, indexes, transactions, and query optimization.", 0.91),
    Course("db-003", "MongoDB — The Complete Developer's Guide", "Udemy / Max Schwarzmüller",
           "https://www.udemy.com/course/mongodb-the-complete-developers-guide/",
           ["mongodb", "nosql", "databases"],
           "beginner", "CRUD, aggregation pipeline, Atlas, Mongoose, and indexing.", 0.89),
    Course("db-004", "Redis Bootcamp for Beginners", "Udemy",
           "https://www.udemy.com/course/redis-bootcamp-for-beginners/",
           ["redis", "nosql", "databases"],
           "beginner", "Caching, pub/sub, sorted sets, streams, and Redis with Python/Node.", 0.83),
    Course("db-005", "Pinecone Vector Database Fundamentals", "Pinecone Docs",
           "https://docs.pinecone.io/guides/get-started/overview",
           ["vector_db", "llm", "embeddings", "databases"],
           "beginner", "Official Pinecone guide: indexes, namespaces, metadata filtering, hybrid search.", 0.85),

    # --- Security ---
    Course("sec-001", "The Complete Cyber Security Course: Hackers Exposed!", "Udemy",
           "https://www.udemy.com/course/the-complete-internet-security-privacy-course-volume-1/",
           ["security", "cybersecurity"],
           "beginner", "Threat landscape, encryption, firewalls, network security, and anonymity.", 0.85),
    Course("sec-002", "OAuth 2.0 and OpenID Connect (in plain English)", "OktaDev",
           "https://www.youtube.com/watch?v=996OiexHze0",
           ["security", "auth", "api"],
           "intermediate", "Free, authoritative 1-hour video on OAuth flows and OIDC.", 0.90),
    Course("sec-003", "Application Security and OWASP Top 10", "Pluralsight",
           "https://www.pluralsight.com/courses/application-security-owasp-top-10",
           ["security", "api", "web"],
           "intermediate", "OWASP Top 10 with code examples. SQL injection, XSS, CSRF, and more.", 0.87),

    # --- Product / Leadership ---
    Course("pm-001", "Become a Product Manager", "Udemy",
           "https://www.udemy.com/course/become-a-product-manager-learn-the-skills-get-a-job/",
           ["product_management", "leadership"],
           "beginner", "End-to-end product lifecycle: user research, roadmaps, metrics, and launches.", 0.88),
    Course("pm-002", "Product Analytics Certification", "Mixpanel",
           "https://mixpanel.com/learn/",
           ["product_management", "analytics"],
           "beginner", "Free Mixpanel certification on funnel analysis, retention, and cohort studies.", 0.83),
    Course("pm-003", "Technical Writing for Engineers", "Google",
           "https://developers.google.com/tech-writing/one",
           ["communication", "writing"],
           "beginner", "Free Google course on clear technical documentation.", 0.86),
    Course("pm-004", "Stakeholder Management", "LinkedIn Learning",
           "https://www.linkedin.com/learning/stakeholder-management",
           ["leadership", "communication"],
           "intermediate", "Influence without authority, managing up, and conflict resolution.", 0.80),

    # --- Algorithms / Interview ---
    Course("algo-001", "Master the Coding Interview: Data Structures + Algorithms", "Udemy / Andrei Neagoie",
           "https://www.udemy.com/course/master-the-coding-interview-data-structures-algorithms/",
           ["algorithms", "python", "javascript", "interviews"],
           "intermediate", "Big O, arrays, trees, graphs, dynamic programming — with mock interviews.", 0.92),
    Course("algo-002", "Neetcode 150", "Neetcode.io",
           "https://neetcode.io/roadmap",
           ["algorithms", "interviews", "python"],
           "intermediate", "Free curated list of 150 LeetCode problems with video walkthroughs.", 0.95),
    Course("algo-003", "Grokking the Coding Interview Patterns", "Educative",
           "https://www.educative.io/courses/grokking-coding-interview-patterns-python",
           ["algorithms", "interviews", "python"],
           "intermediate", "16 patterns (sliding window, two pointers, BFS/DFS, etc.) with practice.", 0.93),

    # --- Analytics / BI ---
    Course("bi-001", "Tableau Desktop Specialist Certification", "Udemy",
           "https://www.udemy.com/course/tableau-certified-associate/",
           ["analytics", "tableau", "data_visualization"],
           "beginner", "Visualization best practices, calculated fields, dashboards, and certification prep.", 0.86),
    Course("bi-002", "dbt + BigQuery: Analytics Engineering Bootcamp", "Udemy",
           "https://www.udemy.com/course/complete-dbt-data-build-tool-bootcamp-zero-to-hero-learn-dbt/",
           ["analytics_engineering", "dbt", "sql", "bigquery"],
           "intermediate", "Transform raw data into reliable analytics-ready tables with dbt.", 0.87),
    Course("bi-003", "Python for Finance: Algorithmic Trading", "Udemy",
           "https://www.udemy.com/course/python-for-finance-investment-fundamentals-data-analytics/",
           ["python", "finance", "analytics"],
           "intermediate", "Financial data analysis, backtesting, and portfolio optimization in Python.", 0.82),

    # --- Soft skills / Career ---
    Course("career-001", "Negotiation Fundamentals", "Coursera",
           "https://www.coursera.org/learn/negotiation-fundamentals",
           ["negotiation", "communication", "leadership"],
           "beginner", "HEC Paris course on negotiation strategy. Great for salary talks.", 0.83),
    Course("career-002", "Write a Winning Resume and LinkedIn Profile", "LinkedIn Learning",
           "https://www.linkedin.com/learning/writing-a-tech-resume",
           ["career", "communication"],
           "beginner", "Practical advice on tech resumes, ATS optimization, and LinkedIn presence.", 0.78),
]
